# Generated by Django 5.0.6 on 2024-06-04 17:48

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0002_user_gender_user_phone_number_user_picture_and_more'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='AdministratorProfile',
            new_name='Administrator',
        ),
        migrations.RenameModel(
            old_name='InstructorProfile',
            new_name='Instructor',
        ),
        migrations.RenameModel(
            old_name='LearnerProfile',
            new_name='Learner',
        ),
    ]
