# Generated by Django 5.0.6 on 2024-07-10 11:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0010_alter_user_timezone'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='timezone',
            field=models.CharField(choices=[('America/New_York', 'Eastern Time Zone (EST)'), ('America/Chicago', 'Central Time Zone (CST)'), ('America/Los_Angeles', 'Pacific Time Zone (PST)'), ('Europe/London', 'Greenwich Mean Time (GMT)'), ('Asia/Kolkata', 'India Standard Time (IST)')], default='UTC', max_length=50),
        ),
    ]
