# Generated by Django 5.0.6 on 2024-06-30 08:11

import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0003_rename_administratorprofile_administrator_and_more'),
        ('courses', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='ScormCloudRegistration',
            fields=[
                ('registration_id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('course_id', models.CharField(max_length=255)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('learner', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='accounts.learner')),
            ],
        ),
    ]
