# Generated by Django 5.0.6 on 2024-06-30 10:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('courses', '0003_scormcloudcourse_category_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='scormcloudcourse',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True),
        ),
        migrations.AlterField(
            model_name='scormcloudcourse',
            name='updated_at',
            field=models.DateTimeField(auto_now=True),
        ),
    ]
