# Generated by Django 5.0.6 on 2024-06-30 19:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('courses', '0006_remove_scormcloudregistration_course_id_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='scormcloudregistration',
            name='course',
        ),
        migrations.AddField(
            model_name='scormcloudregistration',
            name='course_id',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
