# Generated by Django 5.0.6 on 2024-07-09 08:35

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('courses', '0007_remove_scormcloudregistration_course_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='scormcloudcourse',
            name='price',
        ),
    ]
