# Generated by Django 5.0.6 on 2024-07-09 18:59

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0006_facilitator'),
        ('courses', '0009_scormcloudcourse_published_by'),
    ]

    operations = [
        migrations.CreateModel(
            name='CourseDelivery',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('delivery_code', models.CharField(max_length=50, unique=True)),
                ('delivery_type', models.CharField(choices=[('SELF_PACED', 'Self Paced'), ('INSTRUCTOR_LED', 'Instructor Led')], max_length=20)),
                ('enrollment_type', models.CharField(choices=[('OPEN', 'Open Enrollment'), ('INVITE', 'By Invitation')], max_length=20)),
                ('all_participants_access', models.BooleanField(default=True)),
                ('start_date', models.DateTimeField(blank=True, null=True)),
                ('end_date', models.DateTimeField(blank=True, null=True)),
                ('deactivation_date', models.DateTimeField(blank=True, null=True)),
                ('is_mandatory', models.BooleanField(default=False)),
                ('requires_attendance', models.BooleanField(default=False)),
                ('requires_feedback', models.BooleanField(default=False)),
                ('requires_completion_certificate', models.BooleanField(default=False)),
                ('course', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='deliveries', to='courses.scormcloudcourse')),
                ('facilitators', models.ManyToManyField(related_name='facilitated_deliveries', to='accounts.facilitator')),
                ('participants', models.ManyToManyField(related_name='enrolled_deliveries', to='accounts.learner')),
            ],
        ),
    ]
