# Generated by Django 5.0.6 on 2024-07-09 19:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('courses', '0011_attendance_enrollment_feedback'),
    ]

    operations = [
        migrations.AddField(
            model_name='coursedelivery',
            name='title',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
