# Generated by Django 5.0.6 on 2024-07-09 19:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('courses', '0012_coursedelivery_title'),
    ]

    operations = [
        migrations.AddField(
            model_name='coursedelivery',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, null=True),
        ),
    ]
