# Generated by Django 5.0.6 on 2024-07-09 20:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('courses', '0013_coursedelivery_created_at'),
    ]

    operations = [
        migrations.AlterField(
            model_name='coursedelivery',
            name='deactivation_date',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='coursedelivery',
            name='end_date',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='coursedelivery',
            name='start_date',
            field=models.DateField(blank=True, null=True),
        ),
    ]
