# Generated by Django 5.0.6 on 2024-07-09 23:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('courses', '0015_coursedelivery_end_time_coursedelivery_start_time'),
    ]

    operations = [
        migrations.AddField(
            model_name='coursedelivery',
            name='deactivation_time',
            field=models.TimeField(blank=True, null=True),
        ),
    ]
