# Generated by Django 5.0.6 on 2024-07-10 06:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('courses', '0016_coursedelivery_deactivation_time'),
    ]

    operations = [
        migrations.AddField(
            model_name='scormcloudcourse',
            name='registration_id',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
