# Generated by Django 5.0.6 on 2024-07-12 06:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('courses', '0019_coursedelivery_created_by'),
    ]

    operations = [
        migrations.AddField(
            model_name='coursedelivery',
            name='timezone',
            field=models.CharField(default='UTC', max_length=50),
        ),
    ]
