# Generated by Django 5.0.6 on 2024-07-12 11:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('courses', '0020_coursedelivery_timezone'),
    ]

    operations = [
        migrations.AlterField(
            model_name='scormcloudcourse',
            name='cover_image',
            field=models.ImageField(blank=True, default='https://placehold.co/600x400', null=True, upload_to='course_covers/'),
        ),
    ]
