# Generated by Django 5.0.6 on 2024-07-22 10:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('multitenancy', '0002_tenantrequest_db_host_tenantrequest_db_port'),
    ]

    operations = [
        migrations.AddField(
            model_name='tenantrequest',
            name='cloudscorm_app_id',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='tenantrequest',
            name='cloudscorm_secret_key',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
